apiVersion: v1
data:
  v1_ConfigMap.ca-certs-merged.bbitai-dev: "7312159215"
  v1_ConfigMap.ca-certs-merged.crw: "7298056538"
  v1_ConfigMap.vscode-editor-configurations.bbitai-dev: "7312159210"
  v1_ConfigMap.vscode-editor-configurations.crw: "6891966576"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: workspaces-config
    app.kubernetes.io/managed-by: devspaces-operator
    app.kubernetes.io/part-of: che.eclipse.org
  name: sync-workspaces-config
