apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    toolchain.dev.openshift.com/last-applied-configuration: '{"apiVersion":"v1","kind":"ResourceQuota","metadata":{"labels":{"toolchain.dev.openshift.com/provider":"codeready-toolchain","toolchain.dev.openshift.com/space":"bbitai"},"name":"compute-deploy","namespace":"bbitai-dev"},"spec":{"hard":{"limits.cpu":"30000m","limits.memory":"30Gi","limits.nvidia.com/gpu":0,"requests.cpu":"3000m","requests.memory":"30Gi","requests.nvidia.com/gpu":0},"scopes":["NotTerminating"]}}'
  labels:
    toolchain.dev.openshift.com/provider: codeready-toolchain
    toolchain.dev.openshift.com/space: bbitai
  name: compute-deploy
spec:
  hard:
    limits.cpu: "30"
    limits.memory: 30Gi
    limits.nvidia.com/gpu: "0"
    requests.cpu: "3"
    requests.memory: 30Gi
    requests.nvidia.com/gpu: "0"
  scopes:
  - NotTerminating
