apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: https://github.com/BitaiBence/felho_lab.git
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: felho-lab-git
    app.kubernetes.io/component: felho-lab-git
    app.kubernetes.io/instance: felho-lab-git
    app.kubernetes.io/name: felho-lab-git
    app.kubernetes.io/part-of: felho-lab-git-app
  name: felho-lab-git
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: felho-lab-git
    deployment: felho-lab-git
  sessionAffinity: None
  type: ClusterIP
