apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: workspace411854283d724f9e-sa-dockercfg-xxn22
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: workspace411854283d724f9e-sa-dockercfg-xxn22
  labels:
    controller.devfile.io/devworkspace_id: workspace411854283d724f9e
    controller.devfile.io/devworkspace_name: felho-lab-ui-nmek
  name: workspace411854283d724f9e-sa
  ownerReferences:
  - apiVersion: workspace.devfile.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: DevWorkspace
    name: felho-lab-ui-nmek
    uid: 41185428-3d72-4f9e-9943-8000b2a63359
secrets:
- name: workspace411854283d724f9e-sa-dockercfg-xxn22
