apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: photo-service
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: photo-service
  sessionAffinity: None
  type: ClusterIP
