apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: sqlserver
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tds
    port: 1434
    protocol: TCP
    targetPort: 1433
  selector:
    app: sqlserver
  sessionAffinity: None
  type: ClusterIP
