apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
- name: workspace64077fdba975457e-sa-dockercfg-h96bt
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: workspace64077fdba975457e-sa-dockercfg-h96bt
  labels:
    controller.devfile.io/devworkspace_id: workspace64077fdba975457e
    controller.devfile.io/devworkspace_name: terminal-66z78f
  name: workspace64077fdba975457e-sa
  ownerReferences:
  - apiVersion: workspace.devfile.io/v1alpha2
    blockOwnerDeletion: true
    controller: true
    kind: DevWorkspace
    name: terminal-66z78f
    uid: 64077fdb-a975-457e-86d0-4886e97f954a
secrets:
- name: workspace64077fdba975457e-sa-dockercfg-h96bt
